name: FuelTrack
options:
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    PRODUCT_NAME: FuelTrack
    PRODUCT_BUNDLE_IDENTIFIER: com.greeneee.fueltrack.ios
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    DEVELOPMENT_LANGUAGE: en
packages: {}
targets:
  FuelTrack:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Sources/Resources
        type: folder
    info:
      path: Sources/Info.plist
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    prebuildScripts: []
    postbuildScripts: []
schemes:
  FuelTrack:
    build:
      targets:
        FuelTrack: all
    run:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: false
