name: iOS Beta (Fastlane TestFlight)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  beta:
    runs-on: macos-14
    env:
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install Homebrew deps
        run: |
          brew update
          brew install xcodegen

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: fastlane

      - name: Write App Store Connect API key (AuthKey.p8)
        shell: bash
        run: |
          mkdir -p fastlane
          if [ -z "${{ secrets.APP_STORE_CONNECT_KEY_P8 }}" ]; then
            echo "APP_STORE_CONNECT_KEY_P8 secret not set. Skipping beta deployment." && exit 1
          fi
          echo "${{ secrets.APP_STORE_CONNECT_KEY_P8 }}" > fastlane/AuthKey.p8

      - name: Fastlane beta (TestFlight)
        run: |
          cd fastlane
          bundle install --path vendor/bundle
          cd ..
          bundle exec fastlane -f fastlane/Fastfile beta
